### ISSUE TITLE
Indent display equation within a sentence

### ISSUE THREAD

**Issue by kiryph** [dbmrq/vim-bucky#4]
Equations are part of sentences. For example, see this screenshot from Feller on *Probability Theory*:

![screen shot 2018-08-27 at 15 19 23](https://user-images.githubusercontent.com/371756/44661980-a89d2300-aa0c-11e8-8e86-0cd500920497.png)

This is true for all books, articles, ... which use equations.

The tex source code could look like
 ```tex
Thus
   \begin{equation*}
     P\{A_1 \cup A_2\} = \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
   \end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
   least one among $n$ events can be computed by a formula analogous to (7.4),
   derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
   terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
   \begin{equation}
     P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
   \end{equation}
   holds.
In the special case where the events $A_1, A_2, \ldots$ are mutually
```

### Current Behavior
```tex
Thus
\begin{equation*}
   P\{A_1 \cup A_2\} = \frac{1}{2}+\frac{1}{2}-\frac{1}{4}=\frac{3}{4}.
\end{equation*}

The probability $P\{A_1 \cup A_2\cup \cdots A_n\}$ of the realization of at
   least one among $n$  events can be computed by a formula analogous to (7.4),
   derived in IV,1.
Here we note only that the argument leading to (7.3) applies to any number of
   terms.
Thus \emph{for arbitrary events $A_1, A_2, \ldots$ the inequality}
\begin{equation}
   P\{A_1 \cup A_2\cup \cdots \} \leq P\{A_1}+P\{A_2}+\ldots
\end{equation}
holds.
In the special case where the events $A_1, A_2, \ldots$ are mutually
```
Any chance, vim-bucky could also handle these?
I guess the more difficult one is when the period is within the math environment.

**Comment by dbmrq** [comment]
There you go.

I actually study philosophy, I rarely use math in my documents, so I didn't consider those cases. Let me know if there's anything else. :)

**Comment by kiryph** [comment]
Also thanks for this update.

Sorry to bother you with something you do not need.

I noticed following:
As long as the `\begin{}`/`\end{}` lines are already on separate lines it works perfectly.
However, if you have an arbitrarily formatted tex code, e.g. join lines of each paragraph withh `vipJ`,
they are not moved to separate lines.

I do not need this (i.e. no issue from me): when I type them, I always place them on separate lines.
From a standpoint that the formatexpr should reach the same state from different starting points,
one could argue this is missing. *latexindent.pl* is here quite good and has respective options. Help section 6.6 *modifyLineBreaks for environments*:
```yaml
modifyLineBreaks:
    environments:
        BeginStartsOnOwnLine: 1
        BodyStartsOnOwnLine: 1
        EndStartsOnOwnLine: 1
        EndFinishesWithLineBreak: 1
        equation*:
            BeginStartsOnOwnLine: 1
            BodyStartsOnOwnLine: 1
            EndStartsOnOwnLine: 1
            EndFinishesWithLineBreak: 1
```
